version: '3'

services:
  redis:
    image: redis:latest
    container_name: dw_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dw_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: unless-stopped
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dw_redis_commander
    ports:
      - "8088:8081"
    environment:
      - REDIS_HOSTS=local:dw_redis:6379
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data: