export enum OtpType {
  RESET_PASSWORD = 'RESET_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
}
