export enum RiskProfileType {
  CONSERVATIVE = 'CONSERVATIVE',
  MODERATELY_CONSERVATIVE = 'MODERATELY_CONSERVATIVE',
  MODERATE = 'MODERATE',
  MODERATELY_AGGRESSIVE = 'MODERATELY_AGGRESSIVE',
  AGGRESSIVE = 'AGGRESSIVE',
} 